TOT calculation to HitFinder / adding flag for method of TOT calculation
JPETTomography/j-pet-framework-examples pull request #168
Opened 2020-08-06 11:39 UTC by kdulski

Moving methods for TOT calculations to HitFinder

Adding flag for selection of the method of the TOT calculations

2020-08-17 10:48 UTC, wkrzemien commented
@kdulski  You probably need to modify cmakes as well. So far the tests are not passing.

2020-08-17 10:49 UTC, wkrzemien commented
@kdulski because of the undefined references

2020-08-17 11:01 UTC, wkrzemien commented on CosmicAnalysis/userParams.json
> +{
Im not 100% sure, but I think we don't add userParams.json to the repo.

2020-08-17 11:03 UTC, wkrzemien commented on CosmicAnalysis/PARAMETERS.md
> +Type of the calculations of the TOT - it can be standard sum (option "standard"), a extended sum taking into account thresholds differences and calculated as rectangulars (option "rectangular"), addi
Is there a default value?

2020-08-17 11:06 UTC, wkrzemien commented on LargeBarrelAnalysis/HitFinderTools.cpp
> +void HitFinderTools::setTOTCalculationType(std::string type)
`const std::string& type`

2020-08-17 11:09 UTC, wkrzemien commented on LargeBarrelAnalysis/HitFinderTools.cpp
> +    if (type == "rectangular") {
You don't check the  "standard" keyword which should be used I think? Also, probably some warning/error should be given in case of other type is used

2020-08-17 11:18 UTC, wkrzemien commented on LargeBarrelAnalysis/HitFinderTools.h
> +  static TOTCalculationType fTOTCalculationType;
I don't like this member here, it introduces some state of the class, which is not needed. . I would remove it,
And do something like that:
1.Define a function that changes a string to enum:
`static TOTCalculationType getToTCalculationType(const std::string& type); // here the body of setTOT`
but with return at the end.
2.Add explicit argument of `TOTCalculationType`  to calculateTOT e.g:
`static double calculateTOT(const JPetHit& hit, TOTCalculationType type = kSimplified);`
3.When calling calculateTOT, one can use  getToTCalculationType to get the second argument

2020-08-18 10:03 UTC, kdulski commented on CosmicAnalysis/userParams.json
> +{
fixed. Where it should be added?

2020-08-18 12:59 UTC, kdulski commented on LargeBarrelAnalysis/HitFinderTools.h
> +  static TOTCalculationType fTOTCalculationType;
corrected in the new PR

2020-08-18 12:59 UTC, kdulski commented on LargeBarrelAnalysis/HitFinderTools.cpp
> +    if (type == "rectangular") {
Ok, check added

2020-08-18 12:59 UTC, kdulski commented on LargeBarrelAnalysis/HitFinderTools.cpp
> +void HitFinderTools::setTOTCalculationType(std::string type)
applied

2020-08-18 13:00 UTC, kdulski commented on CosmicAnalysis/PARAMETERS.md
> +Type of the calculations of the TOT - it can be standard sum (option "standard"), a extended sum taking into account thresholds differences and calculated as rectangulars (option "rectangular"), addi
added default value : 'standard'

2020-08-20 16:42 UTC, alekgajos commented on CosmicAnalysis/userParams.json
> +{
The json parameter files are downloaded from the server. I will update them if you let me know what I should change - just add 
```
"HitFinder_TOTCalculationType_std":"standard"
```
?

2020-08-24 13:53 UTC, alekgajos commented on CosmicAnalysis/userParams.json
> +{
I have updated all of the userParams.json files at the server.

2020-08-24 15:04 UTC, alekgajos requested changes
Good work! Just two minor comments (in the code) and one general doubt to discuss:
I don't know which is the right approach myself but just started wondering if examples such as PhysicsAnalysis, CosmicsAnalysis and Imaging shouldn't use one of the more advanced TOT calculation methods by default?
What do you think?

2020-08-25 10:57 UTC, kdulski commented
Well, if we use more sophisticated way of calculating TOT in, it will require more control from the user, for example to properly set the thresholds. I would stand by default one, to leave other options for experienced users.

2020-08-25 11:27 UTC, alekgajos commented
You are right about the need for properly provided thresholds in such case. I agree that the standard calculation should be default but what concerns me is that if we also use the default parameter of `calculateTOT`, users may not even see from these examples that there is a possibility to do it in a more sophisticated way. Perhaps it would be better to copy the same user option from the general EventCategorizer to these examples as well so that it's visible that there are other options?

2020-08-25 11:27 UTC, alekgajos commented
You are right about the need for properly provided thresholds in such case. I agree that the standard calculation should be default but what concerns me is that if we also use the default parameter of `calculateTOT`, users may not even see from these examples that there is a possibility to do it in a more sophisticated way. Perhaps it would be better to copy the same user option from the general EventCategorizer to these examples as well so that it's visible that there are other options?

2020-08-25 11:27 UTC, alekgajos commented
You are right about the need for properly provided thresholds in such case. I agree that the standard calculation should be default but what concerns me is that if we also use the default parameter of `calculateTOT`, users may not even see from these examples that there is a possibility to do it in a more sophisticated way. Perhaps it would be better to copy the same user option from the general EventCategorizer to these examples as well so that it's visible that there are other options?

2020-08-25 11:27 UTC, alekgajos commented
You are right about the need for properly provided thresholds in such case. I agree that the standard calculation should be default but what concerns me is that if we also use the default parameter of `calculateTOT`, users may not even see from these examples that there is a possibility to do it in a more sophisticated way. Perhaps it would be better to copy the same user option from the general EventCategorizer to these examples as well so that it's visible that there are other options?

2020-08-25 11:27 UTC, alekgajos commented
You are right about the need for properly provided thresholds in such case. I agree that the standard calculation should be default but what concerns me is that if we also use the default parameter of `calculateTOT`, users may not even see from these examples that there is a possibility to do it in a more sophisticated way. Perhaps it would be better to copy the same user option from the general EventCategorizer to these examples as well so that it's visible that there are other options?

2020-08-25 11:28 UTC, alekgajos commented
You are right about the need for properly provided thresholds in such case. I agree that the standard calculation should be default but what concerns me is that if we also use the default parameter of `calculateTOT`, users may not even see from these examples that there is a possibility to do it in a more sophisticated way. Perhaps it would be better to copy the same user option from the general EventCategorizer to these examples as well so that it's visible that there are other options?

2020-08-26 19:03 UTC, wkrzemien approved these changes
Thanks. looks good for me

2020-08-28 12:57 UTC, kdulski commented
Ok, I think I understand. I will add in Cosmic/Imaging/Physic appropriate flag and TOT calculation type in the next commit.
In addition I updated initialization of the histograms in Cosmic/Imaging/Physic, so they are the same as in LargeBarrelAnalysis

2020-09-02 17:29 UTC, alekgajos approved these changes

2020-09-02 17:29 UTC, merged