Calibration by lifetime
JPETTomography/j-pet-framework-examples pull request #172
Opened 2020-11-03 15:43 UTC by kdulski

This is the first PR with only one of the functionalities added - calibration for a single module (for two sides A and B):
- creating new example with new way of calibration
- introducing two changed Tasks: EventFinder with appropriate histograms added, and CalibrationUnit, which will deal with calibration between modules (or just creation of proper histograms)
- as a temporary solution new folder testcomp, which consist of program for calibration. For now it is only able to calibrate for a single module. 

Calibration program needs additional calibParams.json file which is not added in this commit. It works for my exemplary files so it should be ok. I could provide some of them. 

The rest of the functionalities should be added next week.

2020-12-15 10:46 UTC, alekgajos commented
retest this please

2020-12-15 12:12 UTC, alekgajos requested changes
Thank you, that was a lot of good work!

I have several general comments besides those in the code:
* We could consider creating the AB time diff. histograms in the official EventFinder or HitFinder so that it wouln't be necessary to copy this module here,
* Please add some error handling (in addition to the error messages) in `CalibrationTools` so that the program using it exits when some of the input is incorrect,
* Please run clang-format with our style on all the modified source files,
* I think `testcomp` is not a good name for the directory with calibration code, maybe use e.g. `calibrationProgram`.

2020-12-15 12:12 UTC, alekgajos commented on TimeCalibration_lifetime/README.md
> +where "*" stands for the name of the output file (constructed as LayerId_slotId_FileId, e.g. for the first file measured for first scintillator in the first layer: "Layer1_slot01_1")
Please check if this section does not need an update.

2020-12-15 12:12 UTC, alekgajos commented on TimeCalibration_lifetime/README.md
> +
Please also add a reference to the relevant J-PET report and/or article about this calibration.

2021-01-11 04:29 UTC, kkacprzak requested changes
I appreciate grand amount of work, but there is still a lot to be done. 

Please consider all of the comments to the code and more general redesign of classes and methods. I.e. is a custom `EventFinder` necessary? If yes, make a task with a different name.  
Moreover, it is basically two calibrations in one, which should be performed separately. The clarity of the project would benefit hugely if those two would be separated. 
Also:
- change everywhere time units to [ps]
- add meaningful comments with description of methods and classes, also in-code comments
- avoid code redundancy, as indicated in several places
- prepare unit test for methods, that produce calculable results: `FindMiddle, FindExtremum, , FindPeak, FindMaximum`
- include default json files in repository

2021-01-11 04:29 UTC, kkacprzak commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +unsigned CalibrationTools::FindExtremum(std::vector<double> Vector, int filterHalf, unsigned shiftFromFilterHalf, Side side)
Name of the method is unclear - it returns an integer, which in general refers to a number of bin of the histogram, so maybe something like `estimateExtremumBin`?

2021-01-11 04:29 UTC, kkacprzak commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +    return finalEstimatioOfExtremum;
Move returning of the variable after if statement, so to write it once.

2021-01-11 04:29 UTC, kkacprzak commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +      TGraph *firstDerivative = new TGraph(FirstDerivative.size());
Can you make a separate method with drawing the graphs?

2021-01-11 04:29 UTC, kkacprzak commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +    SecondDerivative.push_back(FirstDerivative[0]);
Replace with `getDerivative()`

2021-01-11 04:29 UTC, kkacprzak commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +std::string NumberToChar(double number, int precision)		//Converting Numbers to char with given preicision
I am fan of comments, but actually in this case name of the method is self-explanatory.

2021-01-11 04:29 UTC, kkacprzak commented on TimeCalibration_lifetime/testcomp/CalibrationTools.h
> +  int fEffectiveLength = 48; // cm
BTW, if default z-position cut is +- 23, should effective length be 46 cm?

2021-01-11 04:29 UTC, kkacprzak commented on TimeCalibration_lifetime/testcomp/CalibrationTools.h
> +#include <TCanvas.h>
Are all those includes necessary in header file or some could be moved to cpp file?

2021-01-11 04:29 UTC, kkacprzak commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +        temp = loadPtreeRoot.get_child(kHistoFileSingleKey);
Is this part necessary? Just put property tree `loadPtreeRoot` to header file as 'fOptionTree' (or sth) and read from it when needed.

2021-02-02 09:48 UTC, kdulski commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +    }
I checked it finally. I corrected to the version of code that worked for you, but probably they both should work for proper distributions as the first derivative should have symmetric distribution around the edge. However in the version above if there were some disturbance in the distribution of the first derivative it could estimate wrong point, Thank you for noting that.

2021-02-09 14:44 UTC, kdulski commented on TimeCalibration_lifetime/EventFinder.cpp
> +  getStatistics().createHistogramWithAxes(
Ok, I agree, this is done in the newest commit

2021-02-09 14:45 UTC, kdulski commented on TimeCalibration_lifetime/EventFinder.cpp
> +	std::vector<JPetSigCh> sigALead = Hit.getSignalA().getRecoSignal().getRawSignal().getPoints(JPetSigCh::Leading, JPetRawSignal::ByThrNum);
Ok sure

2021-02-09 14:45 UTC, kdulski commented on TimeCalibration_lifetime/testcomp/CalibrationTools.h
> +  const std::string kEffectiveLengthKey = "Effective_Length_int";
You are right

2021-02-09 14:46 UTC, kdulski commented on TimeCalibration_lifetime/testcomp/CalibrationTools.h
> +  int fEffectiveLength = 48; // cm
Not exactly, as for PALS calibration one should cut more from the edges as the signal at the edge have a very small probability of creating signal in the opposite photomultiplier that will pass all 4 threshold, that is why this value is slightly smaller that half of the effective length

2021-02-09 14:46 UTC, kdulski commented on TimeCalibration_lifetime/testcomp/Calibrate.cpp
> +    // No file with parameters or calibration option
Yeah, I forgot to do it previously

2021-02-09 14:47 UTC, kdulski commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +      for (int j=2; j<2+fNumberOfScintillators; j++) {
Explanation of some more mysterious parts are added

2021-02-09 14:47 UTC, kdulski commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +        std::cout << "No file with a given name: " << fFileWithParameters << " exiting the program." << std::endl;
It should work correctly, but when I will introduce some tests I will check it once again

2021-02-09 14:48 UTC, kdulski commented on TimeCalibration_lifetime/README.md
> +
Readme and Parameters file updated

2021-02-09 14:49 UTC, kdulski commented on TimeCalibration_lifetime/CalibrationUnit.cpp
> +    while (TDiffAB_Corr >> value1 >> uncert1 >> value2 >> uncert2 >> value3 >> uncert3 >> value4 >> uncert4) {
Good idea, the files should be clearer for the reader.

2021-02-09 14:52 UTC, kdulski commented on TimeCalibration_lifetime/CalibrationUnit.cpp
> +        if (AnnihilationCandidates.size() == 1 && DeexcitationCandidates.size() == 1) {
Not exactly, the cleaniest sample is when there is exactly one pair that was selected as annihilation/deexcitation candidate in an event, and not more pairs. as it creates ambiguity in selecting proper pairs and therefore could influence the time difference spectrum. This condition was developed during analysis and allowed to obtain the best time resolution without any artifacts. I hope that I understood your comment correctly

2021-02-09 14:52 UTC, kdulski commented on TimeCalibration_lifetime/testcomp/CalibrationTools.h
> +#include <TCanvas.h>
Sure, corrected

2021-02-09 14:55 UTC, kdulski commented on TimeCalibration_lifetime/testcomp/CalibrationTools.cpp
> +        temp = loadPtreeRoot.get_child(kHistoFileSingleKey);
I would stay with the convention here to load all parameters at the beginning and just reading already obtained parameters later. It makes the rest of the code more clear without unnecessary getting object later, and just using them, but it is only my opinion. But if needed I can change that.

2021-02-09 14:55 UTC, kdulski commented on TimeCalibration_lifetime/CalibrationUnit.cpp
> +      TDiff_AB = (sigBLead.at(i).getValue() - sigALead.at(i).getValue())/1000;
changed everywhere

2021-02-09 14:56 UTC, kdulski commented on TimeCalibration_lifetime/EventFinder.cpp
> +    new TH2D("TDiff_AB_vs_ID_thr4", "Time difference AB vs scintillator ID for threshold 4", 500, -24.75, 24.25, 200, -0.5 , 199.5),
Great idea, I tried to cover that

2021-02-09 14:58 UTC, kdulski commented
On Redmine: http://sphinx.if.uj.edu.pl/redmine/issues/1419
I had added new params file that should be included in the directory with the code. In addition I would like to ask to add dummyCalibration.txt file either.

I tried to apply every suggestions, code is cleaner. If you have any more suggestions, I am open for them

2021-03-15 07:05 UTC, kkacprzak requested changes
An amazing amount of work - again. I am especially happy with test class for tools and much clearer description of workflow. I posted some minor remarks here or there, but the major concern is the design of Tools class - it would be better if it contained only static methods, no constructor. 
I have an impression that more methods can be tested with unit tests. Please review what more can be done.

2021-03-15 07:08 UTC, kkacprzak commented on TimeCalibration_lifetime/CalibrationUnit.cpp
> +        if (AnnihilationCandidates.size() == 1 && DeexcitationCandidates.size() == 1) {
Ok, that is an additional information, that does not follow from the code itself. Can you add a comment above this if statement, indicating that this is an analysis cut? Do you have some link to a presentation or a memo, that shows this?

2021-03-15 07:14 UTC, kkacprzak commented
Question about building and running tests for this example - I did not see it in the build log, only test for Large Barrel and Image Reco. Where it supposed to be added?

2021-03-22 07:06 UTC, kdulski commented on TimeCalibration_lifetime/PALSCalibrationTask.cpp
> + //   saveEvents(events);
As tools are using only histograms, there is no need to save more structures and to store them. 
I removed commented part in the next commit.

2021-03-22 07:08 UTC, kdulski commented on TimeCalibration_lifetime/PALSCalibrationTask.cpp
> +  auto maxScinID = std::max_element(scinMap.begin(), scinMap.end(), [](const auto& l, const auto& r) { return l.first < r.first; });
Ok thanks, I thought that there is a shorter version, but I was not sure if the scintillators are stored in order.

2021-03-22 07:14 UTC, kdulski commented on TimeCalibration_lifetime/tests/CalibrationToolsTest.cpp
> +  BOOST_REQUIRE_CLOSE(result.Value, 2, kEpsilon);
results.Value is double. Is it will not complicate comparison (some numerical uncertinties)?

2021-03-22 07:17 UTC, kdulski commented on TimeCalibration_lifetime/calibrationProgram/CalibrationTools.cpp
> +//Loop starts from the first bin - zero bin is underflow bin
Sorry, now it should be ok

2021-03-22 07:21 UTC, kdulski commented on TimeCalibration_lifetime/calibrationProgram/CalibrationTools.cpp
> +    finalEstimatioOfExtremum = FindPeak(Arguments, SecondDerivative,
If the first estimation of the extremum is more or less ok, then yes. There is some small part of the distributions (disturbed at the edges) that can produce some different results. However, they need a separate approach and depending on the disturbance different range would be needed.
I added the number of bins as a parameter, but maybe in future I will found some method to deal with problematic scintillators.

2021-03-23 10:21 UTC, kdulski commented on TimeCalibration_lifetime/calibrationProgram/CalibrationTools.h
> +class CalibrationTools {
Well, maybe the name is misleading as the CalibrationTools contains not only tools for calibration but every calibration parameter, and stripping classed would increase the number of arguments for each function.
I understand that tools name should have a proper structure, but maybe we could stay as it is and maybe change the name of the files and classes?

2021-03-23 10:24 UTC, kdulski commented
> Question about building and running tests for this example - I did not see it in the build log, only test for Large Barrel and Image Reco. Where it supposed to be added?

Well if I had done everything properly it should appear in TimeCalibration_lifetime/tests
In above directory I had used
make CalibrationToolsTest.x
command, and it worked ok. Do I need to ass somethind to CMake or elsewhere?

2021-03-28 15:57 UTC, kkacprzak commented on TimeCalibration_lifetime/tests/CalibrationToolsTest.cpp
> +  BOOST_REQUIRE_CLOSE(result.Value, 2, kEpsilon);
yes, this comment should be around line 48, where you have a comparison of two integers, which can be changed to `BOOST_REQUIRE_EQUAL(extremumRight, 69);`

2021-03-28 16:01 UTC, kkacprzak reviewed
The PR looks polished up, well done. A small comment to tests, but nothing more. 
I don't know, what to change to make jenkins run tests, maybe it is the configuration on server that needs to be changed.

2022-02-07 12:30 UTC, merged