Add JPetGojaParser
JPETTomography/j-pet-framework-examples pull request #181
Opened 2021-11-28 19:59 UTC by kamilrakoczy

This PR adds JPetGojaParser that parses GOJA file and converts it to the JPetHit.
Signed-off-by: Kamil Rakoczy <kamilrakoczy1@gmail.com>

2021-11-29 11:17 UTC, wkrzemien commented on ImageReconstruction/JPetGojaParser.cpp
> + *  @copyright Copyright 2018 The J-PET Framework Authors. All rights reserved.
Its a detail. But please update the date to 2021

2021-11-29 11:19 UTC, wkrzemien commented on ImageReconstruction/JPetGojaParser.cpp
> +    hits.push_back(h2);
```suggestion
    std::vector<JPetHit> hits = {h1,h2};
```

2021-11-29 11:20 UTC, wkrzemien commented on ImageReconstruction/JPetGojaParser.h
> + *  @copyright Copyright 2018 The J-PET Framework Authors. All rights reserved.
As above

2021-11-29 11:22 UTC, wkrzemien commented on ImageReconstruction/JPetGojaParser.cpp
> + */
It would be useful to have a small description what this class does e.g. what is expected input and output

2021-11-29 11:23 UTC, wkrzemien requested changes
It looks good! I have only small suggestions.  Also, do you have any example that could be used as a some kind of test e.g. small input and output

2021-12-05 21:08 UTC, kamilrakoczy commented on ImageReconstruction/JPetGojaParser.cpp
> + */
I added it to the header file.

2021-12-05 21:08 UTC, kamilrakoczy commented on ImageReconstruction/JPetGojaParser.cpp
> + *  @copyright Copyright 2018 The J-PET Framework Authors. All rights reserved.
Fixed

2021-12-05 21:08 UTC, kamilrakoczy commented on ImageReconstruction/JPetGojaParser.cpp
> +    hits.push_back(h2);
Fixed

2021-12-05 21:08 UTC, kamilrakoczy commented on ImageReconstruction/JPetGojaParser.h
> + *  @copyright Copyright 2018 The J-PET Framework Authors. All rights reserved.
Fixed

2021-12-05 21:09 UTC, kamilrakoczy commented on ImageReconstruction/JPetGojaParser.cpp
> + */
I added it to the header file.

2021-12-05 21:11 UTC, kamilrakoczy commented
@wkrzemien I've fixed initial comments and yes, I have example input file that could be used as a test, but I haven't added it.

2021-12-28 13:08 UTC, alekgajos requested changes

2021-12-28 13:08 UTC, alekgajos commented on ImageReconstruction/main.cpp
> +    manager.registerTask<ReconstructionTask>("JPetGojaParser");
The template parameter should be `JPetGojaParser`.

2022-01-09 18:21 UTC, kamilrakoczy commented on ImageReconstruction/CMakeLists.txt
> +            ${CMAKE_CURRENT_SOURCE_DIR}/JPetGojaParser.h
Yes, fixed.

2022-01-09 18:21 UTC, kamilrakoczy commented on ImageReconstruction/main.cpp
> +    manager.registerTask<ReconstructionTask>("JPetGojaParser");
Fixed.

2022-01-11 19:02 UTC, alekgajos approved these changes

2022-01-17 09:53 UTC, alekgajos commented
@wkrzemien I approve of this PR, should we merge?

2022-01-24 10:44 UTC, wkrzemien approved these changes

2022-01-24 10:44 UTC, merged