Changing units from [ns] to [ps] in TWC task
JPETTomography/j-pet-framework-examples pull request #188
Opened 2023-01-05 21:06 UTC by kkacprzak

This PR is solving the problem reported on [Redmine](http://sphinx.if.uj.edu.pl/redmine/issues/2017)

More details there.

2023-01-05 21:08 UTC, kkacprzak commented
By mistake, I made the PR to the master branch instead of the develop. How to change that?

2023-01-05 22:01 UTC, wkrzemien commented
@kkacprzak I fixed it

2023-01-05 22:03 UTC, wkrzemien commented on LargeBarrelAnalysis/TimeWindowCreatorTools.cpp
> +vector<JPetSigCh> TimeWindowCreatorTools::buildSigChs(TDCChannel* tdcChannel, const JPetTOMBChannel& tombChannel,
This formatting looks super weird. Maybe it is just a way GitHub shows it.

2023-01-05 22:04 UTC, wkrzemien commented on LargeBarrelAnalysis/TimeWindowCreator.h
> +class TimeWindowCreator : public JPetUserTask
Space before : is not necessary I guess

2023-01-05 23:33 UTC, kkacprzak commented on LargeBarrelAnalysis/TimeWindowCreatorTools.cpp
> +vector<JPetSigCh> TimeWindowCreatorTools::buildSigChs(TDCChannel* tdcChannel, const JPetTOMBChannel& tombChannel,
I think that is the case. I am using clang formatter with our default file. This class was not modified since a long time...

2023-01-20 16:23 UTC, alekgajos requested changes
I think `DummyCalibration.txt` should not be in the repo as it's already among the files automatically downloaded from Sphinx:
http://sphinx.if.uj.edu.pl/framework/ExamplesReformed/LargeBarrelAnalysis/dummyCalibration.txt
Did this file change?

2023-01-23 09:23 UTC, merged